name: C Tests

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y build-essential cmake

            - name: Create Build Environment
              run: cmake -E make_directory build

            - name: Configure CMake
              working-directory: build
              run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug

            - name: Build
              working-directory: build
              run: cmake --build . --target run_tests

            - name: Test
              working-directory: ${{github.workspace}}
              run: bash scripts/run_tests.sh
