name: CI

on:
    push:
        branches: [main, master]
    pull_request:
        branches: [main, master]

jobs:
    build-and-test-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

            - name: Run tests
              working-directory: ./
              run: ./scripts/run_test.bat
